server:
    port: ${PORT:${SERVER_PORT:0}}
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://172.20.0.3:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
    application:
        zipkin: http://192.168.1.10:9411