server:
    port: 8080 
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://springeureka:8761/eureka
    instance:
        hostname: springeureka
spring:
    application:
        zipkin: http://zipkin:9411
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
               - id: user-service
                 uri: lb://user-service
                 predicates:
                    - Path=/user/**
               - id: car-service
                 uri: lb://car-service
                 predicates:
                    - Path=/car/**
               - id: bike-service
                 uri: lb://bike-service
                 predicates:
                    - Path=/bike/**
        