server:
    port: 8080 
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
spring:
    application:
        zipkin: http://localhost:9411
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
               - id: user-service
                 uri: lb://user-service
                 predicates:
                    - Path=/user/**
                 filters: 
                    - AuthFilter
               - id: car-service
                 uri: lb://car-service
                 predicates:
                    - Path=/car/**
                 filters: 
                    - AuthFilter
               - id: bike-service
                 uri: lb://bike-service
                 predicates:
                    - Path=/bike/**
               - id: auth-service
                 uri: lb://auth-service
                 predicates:
                    - Path=/auth/**
        